name: Docker Image CI

on:
 push:
   paths:
     - 'scripts/**'
     - 'Dockerfile-for-github-action'
     - 'requirements.txt'
     - 'example.env'
     - '.github/workflows/docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} registry.cn-beijing.aliyuncs.com --password-stdin

    - name: Build and push Docker image
      run: |
        PLATFORMS=linux/arm64,linux/amd64
        DOCKER_IMAGE=registry.cn-beijing.aliyuncs.com/sgcc_electricity
        docker buildx build --platform $PLATFORMS -t $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:1.3.2 --file Dockerfile-for-github-action --push .
